# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5355f242d0a805e07211f340452aaa77a588eaa1d7f5098784ccaacbba908e382873bb6760a7914e8669614765a8c3f52a2e233b760a97de664816cd3c4e91b4

test:
  secret_key_base: 09e4d7f67db758acf136443b58602bb31aeba0a7985c92eb80396c94a33b46c65bb03b41623e8cf21b1ad72c4320ce0955f41caf021b070dcb08f1c5e9123b12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
